# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:23
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations

from polls.models import Question


def give_all_questions_to_admin(apps, schema):
    user = User.objects.get(username="john")
    questions = Question.objects.all()
    print("test worked")
    for q in questions:
        q.owner = user
        q.save()
        print(q)


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_owner'),
    ]

    operations = [
        migrations.RunPython(give_all_questions_to_admin)
    ]
