# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170410_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
