# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:07
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def slugify_questions(apps, schema):
    Question = apps.get_model("polls", "Question")
    questions = Question.objects.all()
    for q in questions:
        q.slug = slugify(q.question_text)
        q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_slug'),
    ]

    operations = [migrations.RunPython(slugify_questions)
    ]
