# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170412_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
