# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170412_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=20),
        ),
    ]
