# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170416_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=20),
        ),
    ]
